- name: Create services dir
  file:
    path: /opt/potee/
    state: directory

- name: Copy Compose File
  tags: [deploy_tasks]
  copy:
    src: "{{ admin_path }}/docker-compose.yml"
    dest: /opt/potee/docker-compose.yml

- name: Copy Scenario file
  tags: [deploy_tasks]
  copy:
    src: "{{ admin_path }}/.env"
    dest: /opt/potee/.env
- name: add PUBLIC_IP to .env
  lineinfile:
    path: /opt/potee/.env
    line: "PUBLIC_IP={{ inventory_hostname }}"

- name: Copy Scenario file
  tags: [deploy_tasks]
  copy:
    src: "{{ admin_path }}/requirements.txt"
    dest: /opt/potee/requirements.txt

- name: Copy scripts
  tags: [deploy_tasks]
  copy:
    directory_mode: true
    src: "{{ admin_path }}/scripts/"
    dest: /opt/potee/scripts/

- name: Copy Scenario file
  tags: [deploy_tasks]
  copy:
    src: "{{ admin_path }}/scenario.yml"
    dest: /opt/potee/scenario.yml

- name: Create and start services
  tags: [deploy_tasks]
  community.docker.docker_compose:
    project_src: /opt/potee/
  register: output

- ansible.builtin.debug:
    var: output
