- name: Install python3-pip
  package:
    update_cache: yes
    name:
      - python3-pip
    state: latest

- name: Install required system packages
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: latest
    update_cache: yes

- name: GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: repository docker
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: install docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: yes

- name: adding users to group docker
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: "755"

- name: Install compose
  tags: [deploy_tasks]
  pip:
    name:
      - docker
      - docker-compose
    executable: pip

- name: Create services dir
  file:
    path: /opt/potee/
    state: directory

- name: Copy Compose File
  tags: [deploy_tasks]
  copy:
    src: "{{ admin_path }}/docker-compose.yml"
    dest: /opt/potee/docker-compose.yml

- name: Copy Scenario file
  tags: [deploy_tasks]
  copy:
    src: "{{ admin_path }}/.env"
    dest: /opt/potee/.env
- name: add PUBLIC_IP to .env
  lineinfile:
    path: /opt/potee/.env
    line: "PUBLIC_IP={{ inventory_hostname }}"

- name: Copy Scenario file
  tags: [deploy_tasks]
  copy:
    src: "{{ admin_path }}/requirements.txt"
    dest: /opt/potee/requirements.txt

- name: Copy scripts
  tags: [deploy_tasks]
  copy:
    directory_mode: true
    src: "{{ admin_path }}/scripts/"
    dest: /opt/potee/scripts/

- name: Copy Scenario file
  tags: [deploy_tasks]
  copy:
    src: "{{ admin_path }}/scenario.yml"
    dest: /opt/potee/scenario.yml

- name: Create and start services
  tags: [deploy_tasks]
  community.docker.docker_compose:
    project_src: /opt/potee/
  register: output

- ansible.builtin.debug:
    var: output
