# ansible-galaxy collection install amazon.aws
# pip3 install boto3

- name: Minio
  hosts: localhost
  connection: local
  vars:
    dir: scripts
    endpoint_url: http://api.minio.potee.local
    access_key: admin
    secret_key: secretpassword
  tasks:
    - find:
        paths: "{{ dir }}"
        file_type: file
        get_checksum: false
      register: scripts

    - name: Create bucket for scripts
      amazon.aws.s3_bucket:
        endpoint_url: "{{ endpoint_url }}"
        name: "{{ dir }}"
        access_key: "{{ access_key }}"
        secret_key: "{{ secret_key }}"
        encryption: "none"
        state: present

    - name: put checkers scripts
      amazon.aws.s3_object:
        endpoint_url: "{{ endpoint_url }}"
        access_key: "{{ access_key }}"
        secret_key: "{{ secret_key }}"
        encrypt: false
        bucket: "{{ dir }}"
        object: "{{ item.path | basename }}"
        src: "{{ item.path }}"
        #content: "{{ lookup('template', 'templates/object.yaml.j2') }}"
        mode: put
      loop: "{{ scripts.files }}"