version: '3.8'
services:
  deploy:
    build: 
      context: .
    image: explabs/potee-deploy
    command: apply
    environment:
      EMAIL: ivanhahanov13@gmail.com
      DOMAIN: defence.potee.ru
      YC_TOKEN: y0_AgAAAABftBDJAATuwQAAAADPHr-rhzyF3McKR8Oe2UF_75LUACAiwow
      # YC_CLOUD_ID: xxx
      # YC_FOLDER_ID: xxx
    volumes:
      - ./:/platform/

