version: '3.8'
services:
  deploy:
    build: 
      context: .
    image: explabs/potee-deploy
    command: apply
    environment:
      DOMAIN: defence.potee.ru
      # EMAIL: xxx
      # CF_API_TOKEN: xxx
      # YC_TOKEN: <Yandex OAuth Token>
      # YC_CLOUD_ID: xxx
      # YC_FOLDER_ID: xxx
      # BOT_TOKEN: xxx
      
    volumes:
      - ./:/platform/

