version: '3.8'
services:
  deploy:
    build: 
      context: .
    image: explabs/potee-deploy
    command: apply
    environment:
      YC_TOKEN: <Yandex OAuth Token>
      # YC_CLOUD_ID: xxx
      # YC_FOLDER_ID: xxx
    volumes:
      - ./:/platform/

