---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  GIN_MODE: "release"
  PORT: "80"
  REDIS_HOST: "redis-master"
  REDIS_PORT: "6379"
  MONGO_HOST: "mongodb"
  MONGO_USER: {{ .Values.mongo.username }}
  MONGO_DB: {{ .Values.mongo.database }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-minio
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  MINIO_HOST: "minio:9000"

