---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "potee.name" . }}-config
data:
  GIN_MODE: "release"
  PORT: "80"
  REDIS_HOST: "redis-master"
  REDIS_PORT: "6379"
  MONGO_HOST: "mongodb-headless"
  MONGO_USER: {{ .Values.mongo.username }}
  MONGO_DB: {{ .Values.mongo.database }}
  OVPN_HOST: "ovpn-admin"
  OVPN_PORT: "8000"


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "potee.name" . }}-minio
data:
  MINIO_HOST: "minio:9000"

