apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "potee.checkers.fullname" . }}
  labels:
    {{- include "potee.checkers.labels" . | nindent 4 }}
spec:
  {{- if not .Values.checkers.autoscaling.enabled }}
  replicas: {{ .Values.checkers.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "potee.checkers.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.checkers.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "potee.checkers.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.checkers.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "potee.serviceAccountName.checkers" . }}
      securityContext:
        {{- toYaml .Values.checkers.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-checkers
          securityContext:
            {{- toYaml .Values.checkers.securityContext | nindent 12 }}
          image: "{{ .Values.checkers.image.repository }}:{{ .Values.checkers.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.checkers.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.checkers.service.port }}
              protocol: TCP
          envFrom:
          - configMapRef:
              name: {{ include "potee.name" . }}-minio
          - secretRef:
              name: {{ include "potee.name" . }}-minio
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.checkers.resources | nindent 12 }}
      {{- with .Values.checkers.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.checkers.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.checkers.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
