apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "potee.manager.fullname" . }}
  labels:
    {{- include "potee.manager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.manager.replicaCount }}
  selector:
    matchLabels:
      {{- include "potee.manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.manager.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "potee.manager.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.manager.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "potee.serviceAccountName.manager" . }}
      securityContext:
        {{- toYaml .Values.manager.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}-manager
        securityContext:
          {{- toYaml .Values.manager.securityContext | nindent 12 }}
        image: "{{ .Values.manager.image.repository }}:{{ .Values.manager.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.manager.image.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ .Values.manager.service.port }}
            protocol: TCP
        env:
          - name: CHECKER_HOST
            value: "{{ include "potee.checkers.fullname" . }}"
          - name: CHECKER_PORT
            value: "50001"
        envFrom:
          - configMapRef:
              name: {{ include "potee.name" . }}-config
          - secretRef:
              name: {{ include "potee.name" . }}-access
        livenessProbe:
          httpGet:
            path: /ping
            port: http
        readinessProbe:
          httpGet:
            path: /ping
            port: http
        resources:
          {{- toYaml .Values.manager.resources | nindent 12 }}
        volumeMounts:
        - name: scenario
          mountPath: /app/scenario.yml
          subPath: scenario.yml
      volumes:
      - name: scenario
        configMap:
          name: {{ include "potee.name" . }}-scenario
      {{- with .Values.manager.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.manager.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.manager.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
