{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: websocket
  annotations:
    nginx.org/websocket-services: {{ include "potee.events.fullname" . | quote }}
spec:
  ingressClassName: "nginx"
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: {{ include "potee.events.fullname" . | quote }}
            port:
                name: ws