---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "potee.name" . }}-access
data:
  ACCESS_SECRET: {{ .Values.auth.access_secret | b64enc | quote }}
  REFRESH_SECRET: {{ .Values.auth.refresh_secret | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc | quote }}
  MONGO_PASS: {{ .Values.mongo.password | b64enc | quote }}
  

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "potee.name" . }}-minio
data:
  MINIO_ACCESS_KEY: {{ .Values.minio.username | b64enc | quote }}
  MINIO_SECRET_KEY: {{ .Values.minio.password | b64enc | quote }}