---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-access
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  ACCESS_SECRET: {{ .Values.auth.access_secret | b64enc | quote }}
  REFRESH_SECRET: {{ .Values.auth.refresh_secret | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc | quote }}
  MONGO_PASS: {{ .Values.mongo.password | b64enc | quote }}
  

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-minio
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  MINIO_ACCESS_KEY: {{ .Values.minio.username | b64enc | quote }}
  MINIO_SECRET_KEY: {{ .Values.minio.password | b64enc | quote }}