apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-admin
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.admin.service.type }}
  ports:
    - port: {{ .Values.admin.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
