apiVersion: v1
kind: Service
metadata:
  name: {{ include "potee.score.fullname" . }}
  labels:
    {{- include "potee.score.labels" . | nindent 4 }}
spec:
  type: {{ .Values.score.service.type }}
  ports:
    - port: {{ .Values.score.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "potee.score.selectorLabels" . | nindent 4 }}
