apiVersion: v1
kind: Service
metadata:
  name: {{ include "potee.checkers.fullname" . }}
  labels:
    {{- include "potee.checkers.labels" . | nindent 4 }}
spec:
  type: {{ .Values.checkers.service.type }}
  ports:
    - port: {{ .Values.checkers.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "potee.checkers.selectorLabels" . | nindent 4 }}
