apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-score
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.score.service.type }}
  ports:
    - port: {{ .Values.score.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
