{{- if .Values.serviceAccounts.web.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "potee.serviceAccountName.web" . }}
  labels:
    {{- include "potee.web.labels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.web.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}


{{ if .Values.serviceAccounts.auth.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "potee.serviceAccountName.auth" . }}
  labels:
    {{- include "potee.auth.labels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.auth.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}


{{ if .Values.serviceAccounts.admin.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "potee.serviceAccountName.admin" . }}
  labels:
    {{- include "potee.admin.labels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.admin.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}


{{ if .Values.serviceAccounts.score.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "potee.serviceAccountName.score" . }}
  labels:
    {{- include "potee.score.labels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.score.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}


{{ if .Values.serviceAccounts.manager.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "potee.serviceAccountName.manager" . }}
  labels:
    {{- include "potee.manager.labels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.manager.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}


{{ if .Values.serviceAccounts.checkers.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "potee.serviceAccountName.checkers" . }}
  labels:
    {{- include "potee.checkers.labels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.checkers.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}


{{ if .Values.serviceAccounts.entities.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "potee.serviceAccountName.entities" . }}
  labels:
    {{- include "potee.entities.labels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.entities.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}