apiVersion: v1
kind: Service
metadata:
  name: {{ include "potee.auth.fullname" . }}
  labels:
    {{- include "potee.auth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.auth.service.type }}
  ports:
    - port: {{ .Values.auth.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "potee.auth.selectorLabels" . | nindent 4 }}
