apiVersion: v1
kind: Service
metadata:
  name: {{ include "potee.entities.fullname" . }}
  labels:
    {{- include "potee.entities.labels" . | nindent 4 }}
spec:
  type: {{ .Values.entities.service.type }}
  ports:
    - port: {{ .Values.entities.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "potee.entities.selectorLabels" . | nindent 4 }}
