---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openvpn
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openvpn
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openvpn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openvpn
subjects:
- kind: ServiceAccount
  name: openvpn
