- name: Create infrastructure dir
  file:
    path: /opt/potee/
    state: directory

- name: Copy infrastructure
  copy:
    src: "{{ tasks_path }}"
    dest: /opt/potee/
    owner: "{{ username }}"
    group: "{{ username }}"
