- name: Create services dir
  file:
    path: /opt/potee/
    state: directory

- name: Copy Compose File
  tags: [deploy_tasks]
  copy:
    src: "{{ admin_path }}/docker-compose.yml"
    dest: /opt/potee/docker-compose.yml

- name: Generate .env file
  template:
    src: .env.j2
    dest: /opt/potee/.env

- name: Copy Scenario file
  tags: [deploy_tasks]
  copy:
    src: "{{ admin_path }}/requirements.txt"
    dest: /opt/potee/requirements.txt

- name: Copy scripts
  tags: [deploy_tasks]
  copy:
    directory_mode: true
    src: "{{ admin_path }}/scripts/"
    dest: /opt/potee/scripts/

- name: Copy Scenario file
  tags: [deploy_tasks]
  copy:
    src: "{{ admin_path }}/scenario.yml"
    dest: /opt/potee/scenario.yml

- name: Generate passwd file for traefik
  htpasswd:
    path: "/opt/potee/.htpasswd"
    name: "admin"
    password: "{{ password }}"

- name: Create openvpn dir
  file:
    path: /opt/potee/openvpn/setup/
    state: directory

- name: Create openvpn config
  copy:
    src: openvpn.conf
    dest: /opt/potee/openvpn/setup/openvpn.conf

- name: Pull an image
  community.docker.docker_image:
    name: "{{ item }}"
    source: pull
  with_items:
    - traefik:v2.6
    - explabs/potee-auth
    - explabs/potee-entities
    - explabs/potee-scores
    - explabs/potee-admin
    - explabs/potee-manager
    - explabs/potee-runner
    - explabs/potee-sender
    - rabbitmq:3-management-alpine
    - quay.io/minio/minio
    - redis:alpine
    - mongo:5.0
    - flant/ovpn-admin:openvpn-1.7.5
    - flant/ovpn-admin:1.7.5
  async: 100
  poll: 0
  register: _pull_images

- name: Check for images pulled
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: _jobs
  until: _jobs.finished
  retries: 100
  delay: 5
  with_items: "{{ _pull_images.results }}"

- name: Create and start services
  tags: [deploy_tasks]
  community.docker.docker_compose:
    project_src: /opt/potee/
  async: 1000
  poll: 0
  register: admin_services
