version: '3'
services:
  srv1:
    image: explabs/platform-example-service
    hostname: srv2
    ports:
      - "10.0.1.10:2022:22"
    runtime: sysbox-runc
  srv2:
    image: explabs/platform-example-service
    hostname: srv2
    ports:
      - "10.0.1.11:2022:22"
    runtime: sysbox-runc
