- name: Wait 600 seconds for target connection to become reachable/usable
  wait_for_connection:
  
- name: Gather facts
  setup:

- name: Install python3-pip
  package:
    update_cache: yes
    name:
      - python3-pip
    state: latest

- name: Install required system packages
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: latest
    update_cache: yes

- name: GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: repository docker
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: install docker
  apt:
    name: docker-ce
    state: latest
    update_cache: yes

- name: adding users to group docker
  ansible.builtin.user:
    name: ubuntu
    groups: docker
    append: yes

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: "755"

- name: Install pip packages
  pip:
    name:
      - docker
      - docker-compose
      - passlib
    executable: pip
